[package]
name = "part1"
version = "0.1.0"
authors = ["Steven Harms <sharms@snowfoundry.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"